Repository qwat/qwat-data-model, pull requests merged in 2021-12, with the labels that each got.

#344 add document management system tables
  .gitignore
  init_qwat.sh
  ordinary_data/document/document.sql
  update/delta/delta_1.4.0_000_vl_for_SIA_fixes.sql
  update/delta/delta_1.4.0_001_DMS.sql
Labels: Enhancement

#342 Test default directory for delta folder
  update/upgrade_db.sh
Labels: Bug

#343 Fix reverse pipe should switch fk_node_a and fk_node_b, currently it does not
  ordinary_data/pipe/od_pipe_geom.sql
  update/delta/1.4.0_002_fix_pipe_reverse_nodes.sql
Labels: Bug, Data model

#333 add an attribute type to leak
  ordinary_data/leak/od_leak.sql
  update/delta/delta_1.4.0_003_create_fk_leak_type.sql
  value_lists/vl_leak_type.sql
Labels: Enhancement
