Repository qwat/qwat-data-model, pull requests merged in 2022-11, with the labels that each got.

#364 [CI] (re?)enable tests in CI
  .github/workflows/run_tests.yml
  README.md
  init_qwat.sh
  tests/pg_service.conf
  tests/test_add_node.expected.sql
  tests/test_alternative_geometry.expected.sql
  tests/test_altitude.expected.sql
  tests/test_move_node_end_pipe.expected.sql
  tests/test_node_orientation.expected.sql
  tests/test_scenarii.expected.sql
  tests/test_scenarii.sql
  tests/test_scenarii_scalability.model
  tests/test_valve_count.expected.sql
  tests/test_valve_orientation.expected.sql
  tests/tests.sh
  tests/tests_scalability.sh
  tests/tests_scalability_multithread.sh
Labels: 3 - Review

#365 [CI] include pum check in CI to test datamodel upgrades
  .build/customizations/sigip/delta/post-all.py
  .build/customizations/sigip/delta/pre-all.py
  .github/workflows/run_tests.yml
  init_qwat.sh
  requirements.txt
  tests/pg_service.conf
  tests/tests_upgrade.sh
  update/delta/delta_1.2.8_schema_visible_perf.pre.py
  update/delta/delta_1.4.0_002_fix_pipe_reverse_nodes.sql
  update/delta/delta_1.4.0_005_normalize_index_name.sql
  update/delta/post-all.py
  update/delta/pre-all.py
Labels: 3 - Review

#363 Avoid references to productions views directly (prefer tables)
  .build/customizations/sigip/views/damage.sql
  .build/customizations/sigip/views/hydrant.sql
  .build/customizations/sigip/views/installation.sql
  .build/customizations/sigip/views/leak.sql
  .build/customizations/sigip/views/part.sql
Labels: Data model

#366 Set pipe year check >= 1800 instead > 1800 and add some verbosity in init_qwat.sh
  init_qwat.sh
  ordinary_data/pipe/od_pipe.sql
  ordinary_data/views/insert_views.sh
  update/delta/delta_1.4.0_004_fix_pipe_year_check.sql
Labels: Bug
