Repository qwat/qwat-data-model, pull requests merged in 2023-01, with the labels that each got.

#359 Inheritance of attributes on nodes
  .build/customizations/sigip/views/hydrant.sql
  .build/customizations/sigip/views/installation.sql
  .build/customizations/sigip/views/part.sql
  init_qwat.sh
  ordinary_data/functions/fn_node_create.sql
  ordinary_data/functions/fn_node_set_distributors.sql
  ordinary_data/functions/fn_node_set_status.sql
  ordinary_data/functions/fn_pressurezone.sql
  ordinary_data/nodes/od_network_element.sql
  ordinary_data/nodes/od_node.sql
  ordinary_data/pipe/od_pipe_geom.sql
  ordinary_data/views/export/export_hydrant.py
  ordinary_data/views/export/export_installation.py
  ordinary_data/views/export/export_meter.py
  ordinary_data/views/export/export_part.py
  ordinary_data/views/export/export_subscriber.py
  ordinary_data/views/inheritance/od_all_inheritance.py
  tests/test_add_node.sql
  tests/test_altitude.sql
  tests/test_move_node_end_pipe.sql
  tests/test_node_orientation.sql
  tests/test_scenarii.sql
  update/delta/delta_1.4.0_007_node_inheritance_status.sql
  update/delta/delta_1.4.0_008_node_inheritance_distributor.sql
  update/delta/delta_1.4.0_009_node_inheritance_pressurezone.sql
Labels: Enhancement, 2 - Work started <= 5, Data model

#372 Fix rebase issue
  .build/customizations/sigip/views/hydrant.sql
  .build/customizations/sigip/views/installation.sql
  .build/customizations/sigip/views/part.sql
Labels: Bug

#373 Fix upgrade database with audit triggers
  update/upgrade_db.sh
Labels: Bug

#375 Update scalability tests with new field type (fk_distributor)
  tests/test_scenarii_scalability.model
Labels: Bug

#345 Network intervention simulation
  init_qwat.sh
  network/functions/ft_all_pipes.sql
  network/functions/ft_check_node_is_closed_valve.sql
  network/functions/ft_check_node_is_hydrant.sql
  network/functions/ft_check_node_is_valve.sql
  network/functions/ft_check_valve_is_active.sql
  network/functions/ft_check_valve_is_network.sql
  network/functions/ft_check_valve_is_subscriber.sql
  network/functions/ft_create_network.sql
  network/functions/ft_element_valve_status.sql
  network/functions/ft_network_cutoff.sql
  network/functions/ft_pipe_.sql
  network/functions/ft_search_network_and_subscribers.sql
  network/functions/ft_search_opened_valves.sql
  network/functions/ft_search_path.sql
  network/pipe_reference.sql
  network/vw_pipe_reference.sql
  roles.sql
  update/delta/delta_1.4.0_010_search_path.sql
  update/delta/delta_1.4.0_011_search_opened_valves.sql
  update/delta/delta_1.4.0_012_search_network_and_subscribers.sql
Labels: Enhancement
